version: "3.9"

services:
  backend:
    build: companio-companio
    ports:
      - 8000:8000
    volumes:
      - ./companio-backend:/usr/src/app
    depends_on:
      - db
  frontend:
    build: companio-companio
    ports:
      - 3000:3000
    volumes:
      - ./companio-frontend:/usr/src/app
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: companio_boilerplate_user
      POSTGRES_DB: companio_boilerplate_dev
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: